Исправления в документации
aNNiMON/Own-Programming-Language-Tutorial pull request #5
Opened 2019-09-25 15:57 UTC by ortogo

Выполнено:

1. В README.md исправлена ссылка на релиз.
2. Проверка и дополнение примеров в документации.
3. Исправлены описания функций.
4. Создан скрипт для проверки примеров.
5. Исправления в примерах.

2019-09-25 20:42 UTC, aNNiMON requested changes

2019-09-25 20:42 UTC, aNNiMON commented on docs/modules.yml
> -            print sprintf("%-50s %d%% %.2f / %.2f\r", bar, progress, cur / 1048576.0, max / 1048576.0)
Здесь выводилось в мегабайтах с точностью до двух знаков после запятой.
Нужно вернуть. И подписать можно что это мибибайты: `%.2f / %.2f MiB`
Если использовать float(), то нужно подключить модуль types. Но лучше просто поделить на 1048576.0, тогда и приведение к float не понадобится.

2019-09-25 20:42 UTC, aNNiMON commented on docs/modules.yml
> -          bitmap = createImage("http://lorempixel.com/image_output/nature-q-c-640-480-10.jpg")
Лучше вернуть оригинальное, но не с прямой ссылкой, как было, а с дианмической: http://lorempixel.com/640/480/nature

2019-09-27 17:01 UTC, ortogo commented on docs/modules.yml
> -            print sprintf("%-50s %d%% %.2f / %.2f\r", bar, progress, cur / 1048576.0, max / 1048576.0)
dd88939ff1d9ede0763f1aa7d0b1111ef5a820b6

2019-09-27 17:01 UTC, ortogo commented on docs/modules.yml
> -          bitmap = createImage("http://lorempixel.com/image_output/nature-q-c-640-480-10.jpg")
c92b5c2fe94d3e3f616ffb9e62713c5c21a42b0d

2019-09-27 19:24 UTC, merged